# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('tc_id', models.AutoField(primary_key=True, serialize=False)),
                ('tc_name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default='Yes')),
            ],
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('testplan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('testplan_name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default='Yes')),
            ],
        ),
        migrations.CreateModel(
            name='TestScript',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False)),
                ('script_name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default='Yes')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TestPlan')),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='script_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TestScript'),
        ),
    ]
