# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160723_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testscript',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
