# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160723_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='script_id',
        ),
        migrations.RemoveField(
            model_name='testscript',
            name='plan_id',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
        migrations.DeleteModel(
            name='TestPlan',
        ),
        migrations.DeleteModel(
            name='TestScript',
        ),
    ]
