# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testplans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScript',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False)),
                ('script_name', models.CharField(max_length=200)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default='Yes')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testplans.TestPlan')),
            ],
        ),
    ]
