# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testscripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscript',
            name='script_path',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
