# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('testplan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('testplan_name', models.CharField(max_length=200)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default='Yes')),
            ],
        ),
    ]
