# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executions',
            fields=[
                ('exec_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('tc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.TestCase')),
            ],
        ),
    ]
