# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Executions',
            new_name='Execution',
        ),
    ]
