# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_auto_20160723_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('P', 'Pass'), ('F', 'Fail'), ('N', 'No Run'), ('S', 'Skip')], default='N', max_length=1),
        ),
    ]
