# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0004_auto_20160724_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiontc',
            name='status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('NO RUN', 'No Run'), ('SKIP', 'Skip')], default='NO RUN', max_length=6),
        ),
    ]
