# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0005_auto_20160724_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executiontc',
            old_name='created_time',
            new_name='executed_time',
        ),
    ]
