# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testscripts', '0001_initial'),
        ('executions', '0006_auto_20160724_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionTS',
            fields=[
                ('exec_ts_id', models.AutoField(primary_key=True, serialize=False)),
                ('passCount', models.IntegerField(default=0)),
                ('failCount', models.IntegerField(default=0)),
                ('noRunCount', models.IntegerField(default=0)),
                ('totalCount', models.IntegerField(default=0)),
                ('executed_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('exec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executions.Execution')),
                ('script_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testscripts.TestScript')),
            ],
        ),
        migrations.RemoveField(
            model_name='executiontc',
            name='exec_id',
        ),
        migrations.AddField(
            model_name='executiontc',
            name='exec_ts_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='executions.ExecutionTS'),
            preserve_default=False,
        ),
    ]
