# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0007_auto_20160725_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionts',
            name='status',
        ),
        migrations.AddField(
            model_name='executionts',
            name='failCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executionts',
            name='noRunCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executionts',
            name='passCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executionts',
            name='totalCount',
            field=models.IntegerField(default=0),
        ),
    ]
